name: Checks

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Python 3.9 and Windows tests fail because of pyfftw:
        # https://github.com/pyFFTW/pyFFTW/issues/301
        python-version: ['3.7', '3.8']
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install fftw3 libs (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y libfftw3-dev libfftw3-3
    - name: Install fftw3 libs (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install fftw
    - name: Install dependencies
      run: |
        # prerequisites
        python -m pip install --upgrade pip wheel
        python -m pip install codecov coverage flake8 pytest
        # https://github.com/pyFFTW/pyFFTW/issues/252
        pip install numpy cython
        # install dependencies
        pip install -e .
        # show installed packages
        pip freeze
    - name: Test with pytest
      run: |
        coverage run --source=odtbrain -m pytest tests
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Submit code coverage
      run: |
        coverage report -m
        codecov
