name: Release to PyPI

on:  
  push:
    tags:
      - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -e .
    - name: Build and publish
      env:
        TWINE_USERNAME: ci_qpi
        TWINE_PASSWORD: ${{ secrets.PYPI_PWD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --skip-existing dist/*
